networks:
  meow:
    driver: bridge

services:
  backend:
    build: ./api
    ports:
      - "5177:5177"
    networks:
      - meow

  frontend:
    build: ./web
    ports:
      - "5173:5173"
    expose:
      - 5173
    depends_on:
      - backend
    networks:
      - meow
