services:
  frontend:
    build: web/
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_PORT=5173
  backend:
    build: api/
    ports:
      - "5177:5177"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5172;http://+:5173
