networks:
  meow:
    driver: bridge

services:
  frontend:
    build: web/
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_PORT=5173
    networks:
      - meow
  backend:
    build: api/
    ports:
      - "5177:5177"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5172;http://+:5173
    networks:
      - meow
  test:
    build: .
    ports:
      - "9000:9000"
    environment:
      - PLAYWRIGHT_HTML_PORT=9000
      - PLAYWRIGHT_HTML_OUTPUT_DIR="test_out"
      - PLAYWRIGHT_HTML_OPEN="always"
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
    depends_on:
      - frontend
    networks:
      - meow
