name: Deployment pipeline

on:
    push:
      branches: main
    pull_request:
      branches: main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup .NET core
              uses: actions/setup-dotnet@v4
              with: 
                dotnet-version: '9.0.x'
            - name: Restore and Build .NET Backend
              working-directory: ./api
              run: |
                dotnet restore
                dotnet build --configuration Release
            - name: Start .NET Backend
              working-directory: ./api
              run: |
                nohup dotnet run --no-build --configuration Release &
                sleep 10
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - name: Install and Build React Frontend
              working-directory: ./web
              run: |
                npm install
                npm run build
            - name: Start React Frontend
              working-directory: ./web
              run: |
                npm start &
                sleep 10
            - name: Install root dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30
            