name: Tests 

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker Containers
        run: docker compose up --build -d
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run Tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with: 
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  
    